Program (1)
  ExtDefList (1)
    ExtDef (1)
      Specifier (1)
        StructSpecifier (1)
          STRUCT
          LC
          DefList (1)
            Def (1)
              Specifier (1)
                TYPE: int
              DecList (1)
                Dec (1)
                  VarDec (1)
                    ID: a
              SEMI
          RC
      ExtDecList (1)
        VarDec (1)
          ID: x
      SEMI
