Program (1)
  ExtDefList (1)
    ExtDef (1)
      Specifier (1)
        TYPE: int
      FunDec (1)
        ID: main
        LP
        RP
      CompSt (2)
        LC
        DefList (3)
          Def (3)
            Specifier (3)
              TYPE: int
            DecList (3)
              Dec (3)
                VarDec (3)
                  ID: a
            SEMI
        StmtList (4)
          Stmt (4)
            Exp (4)
              Exp (4)
                ID: a
              ASSIGNOP
              Exp (4)
                Exp (4)
                  Exp (4)
                    INT: 1
                  PLUS
                  Exp (4)
                    INT: 2
                RELOP
                Exp (4)
                  INT: 3
            SEMI
          StmtList (5)
            Stmt (5)
              Exp (5)
                Exp (5)
                  ID: a
                ASSIGNOP
                Exp (5)
                  Exp (5)
                    INT: 1
                  AND
                  Exp (5)
                    Exp (5)
                      INT: 2
                    RELOP
                    Exp (5)
                      INT: 3
              SEMI
            StmtList (6)
              Stmt (6)
                Exp (6)
                  Exp (6)
                    ID: a
                  ASSIGNOP
                  Exp (6)
                    Exp (6)
                      ID: a
                    ASSIGNOP
                    Exp (6)
                      INT: 1
                SEMI
        RC
